deps_config := \
	package/feeds/ifx_voice_cpe/teridian-voice-daa-ter1x66/config/Config.in \
	package/feeds/ifx_feeds_ethsw/lq-ethsw-cli/config/Config.in \
	package/feeds/ltq_feeds_wave_mbssid/lq-wave100/config/Config.in \
	package/feeds/lq_feeds_coc/lq-coc-app-pmd/config/Config.in \
	package/feeds/lq_feeds_coc/lq-coc-app-pm/config/Config.in \
	package/feeds/ifx_feeds_dect/ifx_voip/config/Config.in.voip \
	package/feeds/ifx_voice_cpe/ifx-voice-cpe-wineasy/config/Config.in \
	package/feeds/ifx_voice_cpe/ifx-voice-cpe-vmmc-coef-vr9/config/Config.in \
	package/feeds/ifx_voice_cpe/ifx-voice-cpe-vmmc-coef-ar9/config/Config.in \
	package/feeds/ifx_voice_cpe/ifx-voice-cpe-vmmc/config/Config.in \
	package/feeds/ifx_voice_cpe/ifx-voice-cpe-tapidump/config/Config.in \
	package/feeds/ifx_voice_cpe/ifx-voice-cpe-tapidemo/config/Config.in \
	package/feeds/ifx_voice_cpe/ifx-voice-cpe-tapi-duslic_xt-coef/config/Config.in \
	package/feeds/ifx_voice_cpe/ifx-voice-cpe-tapi-duslic_xt/config/Config.in \
	package/feeds/ifx_voice_cpe/ifx-voice-cpe-tapi/config/Config.in \
	package/feeds/ifx_feeds_netcomp_cpe/ifx_utilities/config/Config.in \
	package/feeds/ifx_feeds_netcomp_cpe/ifx_oam/config/Config.in \
	package/feeds/ifx_feeds_netcomp_cpe/ifx_httpd/config/Config.in \
	package/feeds/ifx_feeds_ethsw/ifx-ethsw/config/Config.in \
	package/feeds/ifx_dsl_cpe/ifx-dsl-cpe-mei-danube/Config.in \
	package/feeds/ifx_dsl_cpe/ifx-dsl-cpe-control-vrx/Config.in \
	package/feeds/ifx_dsl_cpe/ifx-dsl-cpe-control-vinax/Config.in \
	package/feeds/ifx_dsl_cpe/ifx-dsl-cpe-control-danube/Config.in \
	package/feeds/ifx_dsl_cpe/ifx-dsl-cpe-api-vrx/Config.in \
	package/feeds/ifx_dsl_cpe/ifx-dsl-cpe-api-vinax/Config.in \
	package/feeds/ifx_dsl_cpe/ifx-dsl-cpe-api-danube/Config.in \
	package/feeds/ifx_feeds_devm_cpe/ifx_devm/config/Config.in \
	package/feeds/ifx_feeds_dect/ifx_dect/config/Config.in.dect \
	package/feeds/ifx_feeds_netcomp_cpe/ifx_config_common_features/config/Config.in \
	package/feeds/ifx_feeds_netcomp_cpe/ifx_IFXAPIs/config/Config.in \
	package/kexec-tools/kexec-config.in \
	package/ifx-tapidemo/Config.in \
	package/block-extroot/Config.in \
	package/uboot-lantiq/Config.in \
	package/uboot-ifxmips/Config.in \
	package/feeds/ifx_feeds_uboot/open_uboot/config/common/Kconfig \
	package/feeds/ifx_feeds_uboot/open_uboot/config/lib/Kconfig \
	package/feeds/ifx_feeds_uboot/open_uboot/config/board/ar10/Kconfig \
	package/feeds/ifx_feeds_uboot/open_uboot/config/board/vr9/Kconfig \
	package/feeds/ifx_feeds_uboot/open_uboot/config/board/amazon_se/Kconfig \
	package/feeds/ifx_feeds_uboot/open_uboot/config/board/danube/Kconfig \
	package/feeds/ifx_feeds_uboot/open_uboot/config/board/ar9/Kconfig \
	package/feeds/ifx_feeds_uboot/open_uboot/config/scripts_platform/Kconfig \
	package/feeds/ifx_feeds_uboot/open_uboot/config/Kconfig \
	package/mac80211/Config.in.rt2x00 \
	package/madwifi/Config.in \
	package/mac80211/Config.in \
	package/mac80211/Config.in.b43legacy \
	package/mac80211/Config.in.b43 \
	package/mac80211/Config.in.ath9k \
	package/ifx-vmmc/Config.in \
	package/ifx-tapi/Config.in \
	package/compcache/Config.in \
	package/ar7-atm/Config.in \
	package/ifxmips-dsl-api/Config.in \
	package/libpcap/Config.in \
	package/feeds/feed_multimedia/ffmpeg/Config.in \
	package/openssl/Config.in \
	package/hostapd/Config.in \
	package/feeds/feed_opensource_apps/samba3/Config.in \
	package/udev/udev-config.in \
	package/feeds/feed_opensource_apps/busybox/config/sysklogd/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/shell/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/selinux/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/runit/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/procps/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/mailutils/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/printutils/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/networking/udhcp/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/networking/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/miscutils/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/util-linux/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/modutils/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/e2fsprogs/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/loginutils/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/init/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/findutils/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/editors/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/debianutils/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/console-tools/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/coreutils/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/archival/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/libbb/Config.src \
	package/feeds/feed_opensource_apps/busybox/config/Config.in \
	package/feeds/feed_opensource_apps/br2684ctl/config/Config.in \
	package/base-files/image-config.in \
	package/kernel/image-config.in \
	tmp/.config-package.in \
	target/toolchain/Config.in \
	target/sdk/Config.in \
	target/imagebuilder/Config.in \
	toolchain/uClibc/Config.version \
	toolchain/glibc/Config.version \
	toolchain/eglibc/Config.version \
	toolchain/gcc/Config.version \
	toolchain/uClibc/Config.in \
	toolchain/glibc/Config.in \
	toolchain/eglibc/config/Config.in \
	toolchain/eglibc/Config.in \
	toolchain/gcc/Config.in \
	toolchain/binutils/Config.in \
	toolchain/Config.in \
	target/linux/ltqcpe/image/Config.in \
	tmp/.config-target.in \
	target/Config.in \
	/home/yangxu/tplink/lantiq_lettuce/tpbsp/lantiq/Config.in.temp

include/config/auto.conf: \
	$(deps_config)


$(deps_config): ;
