#!/bin/sh

mount -a

/bin/mkdir -m 0777 -p /var/lock
/bin/mkdir -m 0777 -p /var/log
/bin/mkdir -m 0777 -p /var/run
/bin/mkdir -m 0777 -p /var/tmp
/bin/mkdir -m 0777 -p /var/Wireless/RT2860AP

#for the dirs of samba and ntfs-3g, zjj, 20111129
/bin/mkdir -m 0777 -p /var/usbdisk
/bin/mkdir -m 0777 -p /var/dev
/bin/mkdir -m 0777 -p /var/samba/lib
/bin/mkdir -m 0777 -p /var/samba/private
/bin/mkdir -m 0777 -p /var/samba/var/locks
cp -p /etc/passwd.bak /var/passwd
/bin/mkdir -m 0777 -p /var/3G
#end by zjj

echo 1 > /proc/sys/net/ipv4/ip_forward
#echo 1 > /proc/sys/net/ipv4/tcp_syncookies
echo 1 > /proc/sys/net/ipv6/conf/all/forwarding

#krammer add for LAN can't continuous ping to WAN when exchenging the routing mode
#bug1126
echo 3 > /proc/sys/net/netfilter/nf_conntrack_icmp_timeout

echo 0 > /proc/sys/net/ipv4/conf/default/accept_source_route
echo 0 > /proc/sys/net/ipv4/conf/all/accept_source_route

echo 4096 > /proc/sys/net/netfilter/nf_conntrack_expect_max
#echo 5120 > /proc/sys/net/netfilter/nf_conntrack_max

echo 5120 > /proc/sys/vm/min_free_kbytes
#for lantiq dsl firmware, wzy, 20120331
#insmod /lib/modules/drv_ifxos.ko
#insmod /lib/modules/drv_dsl_cpe_api.ko debug_level=3
#end by wzy


insmod /lib/modules/kmdir/kernel/drivers/scsi/scsi_mod.ko
insmod /lib/modules/kmdir/kernel/drivers/scsi/sd_mod.ko

insmod /lib/modules/kmdir/kernel/drivers/usb/core/usbcore.ko

#for 3g-dongle, add by zjj, 20120521
mount -t usbfs usbfs /proc/bus/usb/

#insmod /lib/modules/kmdir/kernel/drivers/usb/host/ehci-hcd.ko
#insmod /lib/modules/kmdir/kernel/drivers/usb/host/ohci-hcd.ko
insmod /lib/modules/kmdir/kernel/drivers/usb/storage/usb-storage.ko

insmod /lib/modules/kmdir/kernel/drivers/scsi/scsi_wait_scan.ko

insmod /lib/modules/kmdir/kernel/drivers/usb/host/ifxusb_host.ko


#netfilter modules load
insmod /lib/modules/kmdir/kernel/net/netfilter/nf_conntrack_proto_gre.ko
insmod /lib/modules/kmdir/kernel/net/netfilter/nf_conntrack_pptp.ko
insmod /lib/modules/ipt_STAT.ko

telnetd

#insmod /lib/modules/kmdir/kernel/drivers/net/ifxmips_ppa/platform/vr9/a5/ifxmips_ppa_datapath_vr9_a5.ko
#insmod /lib/modules/kmdir/kernel/drivers/net/ifxmips_ppa/platform/vr9/a5/ifxmips_ppa_hal_vr9_a5.ko
#insmod /lib/modules/kmdir/kernel/drivers/net/ifxmips_ppa/ppa_api/ifx_ppa_api.ko
#insmod /lib/modules/kmdir/kernel/drivers/net/ifxmips_ppa/ppa_api/ifx_ppa_api_proc.ko

#ifconfig eth0 up
#ifconfig lo 127.0.0.1 netmask 255.0.0.0


echo 2 > /proc/sys/vm/overcommit_memory
echo 95 > /proc/sys/vm/overcommit_ratio
echo 250 > /proc/sys/vm/lowmem_reserve_ratio
echo 2 > /proc/sys/vm/dirty_background_ratio
echo 250 > /proc/sys/vm/dirty_writeback_centisecs
echo 10 > /proc/sys/vm/dirty_ratio
echo 16384 > /proc/sys/vm/max_map_count
echo 2 > /proc/sys/vm/page-cluster
echo 70 > /proc/sys/vm/swappiness

#while true;do
#echo 3 > /proc/sys/vm/drop_caches
#sleep 1
#done &
